### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by timscha** [elcamlost/checkmk-php-fpm-plugin#10]
Hi!
I installed version 2.0 of the plugin in check 2.1 - but I cannot find the plugin. After I downloaded it from the git repo and installed it manually everything worked but excepted. But where should I find it normally in checkmk? I searched in the whole wato.

Thanks
Tim

**Comment by timscha** [comment]
Hi @simon-mueller  Thanks.
I have both areas, yes. But I thought it appears also in "Agent rules". But I will try these ones instead. Thanks.

**Comment by timscha** [comment]
Hi @simon-mueller - Thanks. Sorry for the misunderstanding. With "I Don't find the plugin" - I don't mean the checkmk plugin. :) I meant the plugin itself, which need to get on the particular host. I was looking for it in "Other operating systems" and also in the "Agent rules" which I am using for backing my agents.

**Comment by simon-mueller** [comment]
As your site user, please try to find it under `~/local/share/check_mk/agents/plugins/php_fpm_pools`

**Comment by timscha** [comment]
Thank you.
