### ISSUE TITLE
Since upgrading from Buster to Bullseye: /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by 47k** [elcamlost/checkmk-php-fpm-plugin#7]
Got this issue since upgrading from Buster to Bullseye: /usr/bin/env: ‘python’: No such file or directory

Got it - if you change
#!/usr/bin/env python
to 
#!/usr/bin/env python3 

and it is working again

**Comment by adelphi-company** [comment]
This affects the agent plugin

**Comment by elcamlost** [comment]
Thanks!
fix it in cmk 1.0.
